"""Add media_url

Revision ID: 9cbfb3c11fa9
Revises: 88bd9372465e
Create Date: 2026-06-15 12:34:11.135222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbfb3c11fa9'
down_revision: Union[str, Sequence[str], None] = '88bd9372465e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('media_url', sa.String(), nullable=True))
    op.alter_column('direct_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('group_messages', sa.Column('media_url', sa.String(), nullable=True))
    op.alter_column('group_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('group_messages', 'media_url')
    op.alter_column('direct_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('direct_messages', 'media_url')
    # ### end Alembic commands ###
