"""Add user purchases

Revision ID: d157fcb33b3a
Revises: d1f1c2d3e4f5
Create Date: 2026-06-16 07:04:01.941035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd157fcb33b3a'
down_revision: Union[str, Sequence[str], None] = 'd1f1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_purchases_id'), 'user_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_user_purchases_item_id'), 'user_purchases', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_purchases_item_id'), table_name='user_purchases')
    op.drop_index(op.f('ix_user_purchases_id'), table_name='user_purchases')
    op.drop_table('user_purchases')
    # ### end Alembic commands ###
