"""add is_edited

Revision ID: d1f1c2d3e4f5
Revises: 9cbfb3c11fa9
Create Date: 2026-06-15 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f1c2d3e4f5'
down_revision = '9cbfb3c11fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('group_messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE direct_messages SET is_edited = false WHERE is_edited IS NULL')
    op.execute('UPDATE group_messages SET is_edited = false WHERE is_edited IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_messages', 'is_edited')
    op.drop_column('direct_messages', 'is_edited')
    # ### end Alembic commands ###
