"""Add security question fields

Revision ID: f4d3437ed0ff
Revises: d157fcb33b3a
Create Date: 2026-06-17 06:16:32.337992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d3437ed0ff'
down_revision: Union[str, Sequence[str], None] = 'd157fcb33b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer')
    op.drop_column('users', 'security_question')
    # ### end Alembic commands ###
